### ISSUE TITLE
I made a fork that improved the UX

### ISSUE THREAD

**Issue by hrsetyono** [rocklobster-in/bogo#314]
Hi, I love your plugin. The core functionality is great. But the UX can be confusing like how each translation has its own row in the List Table.

So I forked it and added many UI features in https://github.com/pixelstudio-id/bogo-px

The biggest UI changes is combining all translations in one row and added a flag button to manage the translation like shown below:

![](https://raw.github.com/hrsetyono/cdn/master/bogo/bogo-flags.png)

And the biggest **technical changes** is having a global variable that stores all posts that has Locale. This way we don't need to query the DB everytime we want to check whether a Page has locale or not.

With this global variable, it's also feasible to filter the content and replace all links into its locale version, if exist.

Let me know what do you think. Thanks :)

**Comment by takayukister** [comment]
I think this is a great fork, but don't think it should be posted here as an issue.
